# # Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Imran Khan
title: Ph.D. Candidate | Research Assistant 

# title: Boston, Massachussets
email: khan.i@northeastern.edu
website: imranbuet63@github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  imranbuet63
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: imrankhan063
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fa-brands fa-google-scholar
  url: https://scholar.google.com/citations?user=QqftVlIAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/imran_new.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi Everyone, I am Imran Khan and I am from Bangladesh. Currently, I am a Ph.D. student in Computer Engineering at Northeastern University. Before that, I completed my master's in the Department of Electrical and Computer Engineering at Southern Illinois University Carbondale (2020) and I earned my Bachelor of Science in Electrical and Electronic Engineering from Bangladesh University of Engineering and Technology (BUET). Currently, I am working as a Research Assistant in NUWiNS Lab under the supervision of Dr. Dimitrios Koutsonikolas. My research interest involves ensuring end-to-end performance, mobility, and reliablity in 5G/6G networks.

#I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
    
      - <strong>5G Metamorphosis: A Longitudinal Study of 5G Performance from the Beginning.</strong>
        <br> __Imran Khan^__, Omar Basit^, Moinak Ghoshal, Y. Charlie Hu, Dimitrios Koutsonikolas.
        <br><em><mark>IMC 2025</mark></em>
      - <strong>X5G: An Open, Programmable, Multi-vendor, End-to-end, Private 5G O-RAN Testbed with NVIDIA ARC and OpenAirInterface.</strong>
        <br> D Villa^, __Imran Khan^__, Florian Kaltenberger, Nicholas Hedberg, Ruben Soares da Silva, Stefano Maxenti, Leonardo Bonati, Anupa Kelkar, Chris Dick, Eduardo Baena,  Josep M Jornet, Tommaso Melodia, Michele Polese, Dimitrios Koutsonikolas.
        <br><em><mark>arXiv preprint arXiv:2406.15935</mark></em>
      - <strong>On the Predictability of Fine-grained Cellular Network Throughput using Machine Learning Models.</strong>
        <br>Omar Basit^,  Phuc Dinh^,  __Imran Khan^__, Z. Jonny Kong^, Y. Charlie Hu, Dimitrios Koutsonikolas, Myungjin Lee, Chaoyue Liu 
        <br><em><mark>IEEE MASS 2024</mark></em>
      - <strong>How Mature is 5G Deployment? A Cross-Sectional, Year-Long Study of 5G Uplink Performance.</strong>
        <br>__Imran Khan__, Moinak Ghoshal, Joana Angjo, Sigrid Dimce, Mushahid Hussain, Paniz Parastar,
        Yenchia Yu, Claudio Fiandrino, Charalampos Orfanidis, Shivang Aggarwal, Ana C Aguiar,
        Ozgu Alay, Carla F. Chiasserini, Falko Dressler, Y. Charlie Hu, Steven Y. Kox, Dimitrios Koutsonikolas, Joerg Widmer
        <br><em><mark>IFIP Networking 2024</mark></em>
      - <strong>An Open, Programmable, Multi-vendor 5G O-RAN Testbed with NVIDIA ARC and OpenAirInterface.</strong>
        <br>D Villa^, __Imran Khan^__, Florian Kaltenberger, Nicholas Hedberg, Ruben Soares da Silva, Anupa Kelkar, Chris Dick, Stefano Basagni, Josep M Jornet, Tommaso Melodia, Michele Polese, Dimitrios Koutsonikolas.
        <br><em><mark>IEEE INFOCOM NG-OPERA 2024 [Best Paper Runner-Up]</mark></em>
      - <strong>An Experimental Study of Low-Latency Video Streaming over 5G.</strong>
        <br>__Imran Khan__, Tuyen X. Tran, Matti Hiltunen, Theodore Karagioules, Dimitrios Koutsonikolas.
        <br><em><mark>IEEE MeditCom 2024</mark></em>
      - <strong>Can 5G mmWave Enable Edge-Assisted Real-Time Object Detection for Augmented Reality?</strong>
        <br>Moinak Ghoshal, Z Jonny Kong, Qiang Xu, Zixiao Lu, Shivang Aggarwal, **Imran Khan**, Jiayi Meng, Yuanjie Li, Y Charlie Hu, Dimitrios Koutsonikolas.
        <br><em><mark>IEEE MASCOTS 2023</mark></em>
      - <strong>Performance of Cellular Networks on the Wheels.</strong>
        <br>__Imran Khan^__, Moinak Ghoshal^, Jonny Kong^, Phuc Dinh, Jiayi Meng, Y. Charlie Hu, Dimitrios Koutsonikolas.
        <br><em><mark>ACM IMC, 2023</mark></em>
      - <strong>Demo: NextG-up: a tool for measuring uplink performance of 5G networks. </strong>
        <br>**Imran Khan^**, Moinak Ghoshal^, Qiang Xu^, Z. Jonny Kong, Y. Charlie Hu, and Dimitrios Koutsonikolas. 
        <br><em><mark>ACM Mobisys, 2022</mark></em>
      - <strong>MuSher: An Agile Multipath-TCP Scheduler for Dual-Band 802.11ad/ac Wireless LANs.</strong> 
        <br>S. Aggarwal, S. K. Saha, **Imran Khan**, R. Pathak, D. Koutsonikolas and J. Widmer.
        <br><em><mark>IEEE/ACM Transactions on Networking, 2022</mark></em>
      - <strong>An In-Depth Study of Uplink Performance of 5G mmWave Networks.</strong>
        <br>Moinak Ghoshal, Z. Jonny Kong, Qiang Xu, Zixiao Lu, Shivang Aggarwal, **Imran Khan**, Yuanjie Li, Y. Charlie Hu, Dimitrios Koutsonikolas.
        <br><em><mark>ACM SIGCOMM 5G-MEMU, 2022</mark></em>
      - <strong>Multipath TCP in Smartphones Equipped with Millimeter Wave Radios.</strong>
        <br>**Imran Khan**, Moinak Ghoshal, Shivang Aggarwal, Dimitrios Koutsonikolas, Joerg Widmer. 
        <br><em><mark>ACM WiNTECH, 2021</mark></em>
      - <strong>Efficient Bandwidth Aggregation with MPTCP for Connected Vehicles.</strong> 
        <br>**Imran Khan**, K. Chen.
        <br><em><mark>IEEE Internet of Things, 2021</mark></em>
      - <strong>Bandwidth-need driven energy efficiency improvement of MPTCP users in wireless networks.</strong>
        <br>M. R. Palash, K. Chen, **Imran Khan**.
        <br><em><mark>IEEE Trans. Green Commun. Netw., 2019</mark></em>
      - <strong>Towards Efficient, Work-Conserving, and Fair Bandwidth Guarantee in Cloud Datacenters.</strong>
        <br>B. S. Ali, K. Chen and **Imran Khan**.
        <br><em><mark>IEEE Access, 2019</mark></em>


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AT&T Labs, Inc.
        link: https://about.att.com/sites/labs
        # link_text: boringcompany.com
        sub_title: Research Intern
        caption: June 2021 - August 2021
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Investigated performnce of low-latency video streaming over cellular networks in a joint project with Facebook. The purpose of this study was to correlate RAN side KPIs with application layer metrics to enhance user Quality of Experience (QoE). 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Northeastern University
        caption: 2020 - Present
        sub_title: Ph.D. in Computer Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I am part of NuWINS lab and also affiliated with the Northeastern Institure for the Wireless Internet of Things (WIoT). As part of the WIoT I am involved in developing next generation cellular networks/testbeds. Besides, my other projects involve ensuring end to end performance, mobility, reliability and consistency of performance of mmWave cellular in current 5G. 
      
      - layout: left
        title:  Southern Illinois University Carbondale
        caption: 2018 - 2020
        sub_title: Master's in Computer Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I was part of the Ubiquitous Networking & Computing lab where I was involved with investigating Multi-Path TCP (MPTCP) performance in heterogenous networks.

      - layout: left
        title:  Bangladesh University of Engineering and Technology (BUET)
        sub_title: B.Sc. in Electrical and Electronics Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
               Bangladesh University of Engineering and Technology (BUET) is one of the top enginnering schools in Bangladesh.
  
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Python, C/C++, Android (Java/Kotlin), HTML, CSS

  - title: Dataset | Software 
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [Dataset](https://github.com/NUWiNS/ifip2024_year_long_5G_uplink_study){:target="_blank"}{:rel="noopener noreferrer"} : for Cross-Sectional, Year-Long Study of 5G Uplink Performance. [IFIP 2024]
      - [Dataset](https://github.com/NUWiNS/MASS_2024_Throughput_Prediction){:target="_blank"}{:rel="noopener noreferrer"} : for Predictability of Fine-grained Cellular Network Throughput using Machine Learning Models. [IEEE MASS 2024]
      - [X5G](https://x5g.org){:target="_blank"}{:rel="noopener noreferrer"} : Our first ORAN-Compliant Multi-Vendor 5G testbed.
      - [Dataset](https://github.com/NUWiNS/imc2023-cellular-network-performance-on-wheels-data){:target="_blank"}{:rel="noopener noreferrer"} for 5G network performance on the wheels. [ACM IMC 2023]
      - Android app [NextG-UP](https://dl.acm.org/doi/pdf/10.1145/3498361.3539694){:target="_blank"}{:rel="noopener noreferrer"} app for a crowd-sourcing based measurement study of 5G uplink performance evolution.
      - MPTCP [source code](https://github.com/NUWiNS/ROGII_MPTCP/tree/master}}){:target="_blank"}{:rel="noopener noreferrer"} for an ROG Phone 2, from our WiNTECH 2021 paper.
      - MPTCP [source code](https://github.com/imranbuet63/proton_mptcp){:target="_blank"}{:rel="noopener noreferrer"} for Pixel-5 Phone.

  - title: CV
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Here is my [CV](/assets/IMRAN_CV_Academic.pdf).

  - title: Awards and Professional Service
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Reviewer Internet of Things 2024
      - Reviewer Computer Networks 2024
      - Web-Chair IEEE LANMAN 2024
      - TPC Member IEEE WCNC 2024
      - Reviewer IEEE ICC 2024
      - Web-Chair IEEE WoWMoM 2023
      - Got selected for NSF Funded Student travel grant for Mobicomâ€™2021
      - Reviewer Globecom 2021
      - Reviewer 5G-MEMU Sigcomm WorkShop 2021
      - Got selected for NSF Funded POWDER Network and Wireless Week, Salt Lake City , Utah 2019

    # Look at this cool image  
    # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

navigation:
  - title: Home
    url: /
  - title: New Page
    url: /new-page
